import { StyleSheet } from 'react-native';

export const theme = {
  primary: '#C62828',
  background: '#FFF5F5',
  text: '#1C1C1C',
  muted: '#7A7A7A',
  card: '#FFFFFF',
  accent: '#FF7043',
  border: '#FFD1D1',
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: theme.background,
    alignItems: 'center',

  },
  pageWrapper: {
    flex: 1,
    position: 'relative',
    width: '100%',
    alignItems: 'center',
  },
  backgroundGlow: {
    position: 'absolute',
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: '#FFCDD2',
    top: -80,
    right: -40,
    opacity: 0.35,
    alignSelf: 'center',
  },
  hero: {
    paddingHorizontal: 24,
    paddingTop: 28,
    paddingBottom: 22,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    boxShadow: '0px 10px 18px 0px rgba(198, 40, 40, 0.25)',
  },
  heroCompact: {
    paddingHorizontal: 16,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
  },
  heroHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 16,
    flexWrap: 'wrap',
    width: '100%',
  },
  heroHeaderCompact: {
    flexDirection: 'column',
  },
  heroTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  heroLabel: {
    color: '#FFDADA',
    fontSize: 14,
    marginBottom: 4,
  },
  heroTitle: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 4,
  },
  heroSubtitle: {
    color: '#FFECEC',
    fontSize: 14,
  },
  heroBadge: {
    backgroundColor: '#fff',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'flex-start',
  },
  heroBadgeText: {
    color: '#C62828',
    fontWeight: '700',
  },
  container: {
    flex: 1,
    width: '100%',
  },
  contentContainer: {
    padding: 24,
    gap: 16,
    paddingBottom: 40,
  },
  contentCompact: {
    paddingHorizontal: 16,
    gap: 12,
  },
  section: {
    backgroundColor: theme.card,
    borderRadius: 18,
    padding: 18,
    boxShadow: '0px 6px 10px 0px rgba(0, 0, 0, 0.08)',
    elevation: 4,
    borderWidth: 1,
    borderColor: theme.border,
  },
  sectionCompact: {
    borderRadius: 16,
    padding: 14,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.text,
    marginBottom: 12,
  },
  sectionSubtitle: {
    color: theme.muted,
    marginBottom: 12,
  },
  profileLabel: {
    color: theme.muted,
    fontSize: 13,
    marginBottom: 2,
  },
  profileField: {
    marginBottom: 14,
  },
  profileInput: {
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 16,
    color: theme.text,
    backgroundColor: '#FFFFFF',
  },
  profileInputMultiline: {
    minHeight: 72,
    textAlignVertical: 'top',
  },
  profileInputError: {
    borderColor: '#E53935',
  },
  profileHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  editProfileButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: theme.primary,
  },
  editProfileButtonText: {
    color: theme.primary,
    fontWeight: '600',
  },
  unsavedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#F57C00',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  unsavedBadgeText: {
    color: '#FFF8E1',
    fontWeight: '600',
  },
  profileActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 8,
  },
  profileSaveButton: {
    flexGrow: 1,
    backgroundColor: theme.primary,
    borderRadius: 14,
    alignItems: 'center',
    paddingVertical: 12,
    minWidth: 160,
  },
  profileSaveButtonText: {
    color: '#fff',
    fontWeight: '700',
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  profileStatusRow: {
    marginTop: 10,
  },
  profileStatusText: {
    color: theme.muted,
    fontSize: 13,
  },
  profileStatusError: {
    color: '#D32F2F',
    fontSize: 13,
    marginTop: 4,
  },
  inlineSelectRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  inlineSelectOption: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.border,
  },
  inlineSelectOptionActive: {
    borderColor: theme.primary,
    backgroundColor: '#FFE3E3',
  },
  inlineSelectText: {
    color: theme.text,
    fontWeight: '500',
  },
  inlineSelectTextActive: {
    color: theme.primary,
    fontWeight: '700',
  },
  blockTitle: {
    marginTop: 16,
    marginBottom: 10,
    color: theme.text,
    fontWeight: '600',
  },
  skillEditor: {
    gap: 12,
  },
  skillCategoryCard: {
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 18,
    padding: 14,
    backgroundColor: '#fff',
    gap: 12,
  },
  skillCategoryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  skillCategoryTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: theme.text,
  },
  skillCategoryMeta: {
    color: theme.muted,
    marginTop: 2,
  },
  skillCategoryBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: '#FFECEC',
  },
  skillCategoryBadgeText: {
    color: theme.primary,
    fontWeight: '600',
    fontSize: 12,
  },
  skillRow: {
    borderWidth: 1,
    borderColor: '#FFE0E0',
    borderRadius: 14,
    padding: 12,
    gap: 8,
  },
  skillRowHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  skillName: {
    fontWeight: '600',
    color: theme.text,
  },
  skillRatingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: '#FFF8E1',
  },
  skillRatingValue: {
    fontWeight: '700',
    color: '#FF8F00',
  },
  skillTagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  skillTag: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: '#F5F5F5',
  },
  skillTagText: {
    color: theme.muted,
    fontSize: 12,
    fontWeight: '600',
  },
  skillSlider: {
    width: '100%',
  },
  skillLevelHint: {
    fontSize: 12,
    color: theme.muted,
  },
  skillUsageRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  skillUsagePill: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: '#FFF5F5',
  },
  skillUsageText: {
    color: theme.primary,
    fontSize: 11,
    fontWeight: '600',
  },
  skillGrowButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: theme.primary,
  },
  skillGrowButtonActive: {
    backgroundColor: '#FFE3E3',
  },
  skillGrowButtonText: {
    color: theme.primary,
    fontWeight: '600',
  },
  chipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  chipsRowCompact: {
    gap: 6,
  },
  chip: {
    backgroundColor: theme.primary,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 999,
  },
  chipOutline: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: theme.primary,
  },
  chipText: {
    color: '#fff',
    fontWeight: '600',
  },
  chipTextOutline: {
    color: theme.primary,
  },
  contactCard: {
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.border,
    marginBottom: 12,
  },
  contactCardCompact: {
    padding: 12,
  },
  contactPreferred: {
    borderColor: theme.primary,
    backgroundColor: '#FFE3E3',
  },
  contactLabel: {
    color: theme.muted,
    fontSize: 13,
  },
  contactValue: {
    color: theme.text,
    fontSize: 16,
    fontWeight: '600',
    marginTop: 4,
  },
  contactBadge: {
    marginTop: 6,
    fontSize: 12,
    color: theme.primary,
    fontWeight: '600',
  },
  jobCard: {
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
  },
  jobCardCompact: {
    padding: 14,
  },
  jobTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: theme.text,
  },
  jobCompany: {
    color: theme.muted,
    marginTop: 4,
  },
  jobSalary: {
    color: theme.primary,
    fontSize: 16,
    fontWeight: '600',
    marginTop: 8,
  },
  tagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
    marginBottom: 12,
  },
  tag: {
    backgroundColor: '#FFECEC',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  tagText: {
    color: theme.primary,
    fontSize: 12,
    fontWeight: '600',
  },
  availabilityPlanner: {
    gap: 16,
  },
  availabilityPlannerCompact: {
    gap: 12,
  },
  shiftCalendarRow: {
    flexDirection: 'row',
    gap: 12,
    paddingBottom: 4,
  },
  shiftCalendarItem: {
    width: 150,
    borderRadius: 16,
    borderWidth: 1,
    padding: 12,
    gap: 4,
  },
  shiftCalendarItem_booked: {
    backgroundColor: '#FFE3E3',
    borderColor: '#FFC1C1',
  },
  shiftCalendarItem_open: {
    backgroundColor: '#F1F8E9',
    borderColor: '#C5E1A5',
  },
  shiftCalendarItem_rest: {
    backgroundColor: '#E3F2FD',
    borderColor: '#90CAF9',
  },
  shiftCalendarDay: {
    fontWeight: '700',
    color: theme.text,
  },
  shiftCalendarDate: {
    color: theme.muted,
    fontSize: 12,
    marginBottom: 4,
  },
  shiftCalendarTitle: {
    color: theme.text,
    fontWeight: '600',
  },
  shiftCalendarHours: {
    color: theme.primary,
    fontWeight: '600',
  },
  shiftCalendarLoading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    gap: 10,
  },
  shiftCalendarLoadingText: {
    color: theme.muted,
    fontSize: 14,
  },
  shiftCalendarActionBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: theme.border,
  },
  shiftCalendarActionText: {
    color: theme.primary,
    fontSize: 11,
    fontWeight: '600',
  },
  weekMatrixWrapper: {
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 18,
    overflow: 'hidden',
  },
  weekMatrixHeader: {
    flexDirection: 'row',
    backgroundColor: '#FFF0F0',
  },
  weekMatrixCornerCell: {
    width: 90,
    padding: 10,
    borderRightWidth: 1,
    borderRightColor: theme.border,
    justifyContent: 'center',
  },
  weekMatrixLegend: {
    fontSize: 12,
    color: theme.muted,
  },
  weekMatrixHeaderCell: {
    flex: 1,
    padding: 10,
    borderRightWidth: 1,
    borderRightColor: theme.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  weekMatrixHeaderText: {
    fontWeight: '600',
    color: theme.text,
  },
  weekMatrixRow: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: theme.border,
  },
  weekMatrixLabelCell: {
    width: 90,
    padding: 10,
    borderRightWidth: 1,
    borderRightColor: theme.border,
  },
  weekMatrixLabel: {
    fontWeight: '600',
    color: theme.text,
  },
  weekMatrixHours: {
    fontSize: 12,
    color: theme.muted,
  },
  weekMatrixCell: {
    flex: 1,
    aspectRatio: 1.2,
    borderRightWidth: 1,
    borderRightColor: theme.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  weekMatrixCellActive: {
    backgroundColor: '#C62828',
  },
  templatesRow: {
    gap: 10,
  },
  templateButton: {
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 14,
    padding: 12,
    backgroundColor: '#fff',
  },
  templateButtonActive: {
    borderColor: theme.primary,
    backgroundColor: '#FFECEC',
  },
  templateButtonLabel: {
    fontWeight: '600',
    color: theme.text,
  },
  templateButtonHint: {
    color: theme.muted,
    fontSize: 12,
    marginTop: 2,
  },
  vacationBanner: {
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 16,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
  },
  vacationBannerActive: {
    borderColor: '#80CBC4',
    backgroundColor: '#E0F2F1',
  },
  vacationBannerBody: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  vacationBannerTitle: {
    fontWeight: '700',
    color: theme.text,
  },
  vacationBannerDates: {
    color: theme.muted,
    fontSize: 12,
  },
  vacationBannerAction: {
    color: theme.primary,
    fontWeight: '700',
  },
  workerCard: {
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 18,
    padding: 18,
    marginBottom: 12,
    backgroundColor: '#fff',
    gap: 8,
  },
  workerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  workerName: {
    fontWeight: '700',
    color: theme.text,
    fontSize: 17,
  },
  workerRole: {
    color: theme.muted,
  },
  workerRating: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  workerRatingText: {
    color: theme.primary,
    fontWeight: '700',
  },
  workerMeta: {
    color: theme.text,
    fontWeight: '600',
  },
  workerAvailability: {
    color: theme.muted,
  },
  badgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  badgePill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: '#FFECEC',
  },
  badgePillText: {
    color: theme.primary,
    fontSize: 12,
    fontWeight: '600',
  },
  workerSkills: {
    color: theme.text,
  },
  workerButton: {
    marginTop: 6,
    backgroundColor: theme.primary,
    paddingVertical: 12,
    borderRadius: 14,
    alignItems: 'center',
  },
  workerButtonText: {
    color: '#fff',
    fontWeight: '700',
  },
  closedCard: {
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    backgroundColor: '#fff',
    gap: 6,
  },
  closedHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  closedTitle: {
    color: theme.text,
    fontWeight: '700',
    flex: 1,
  },
  closedDate: {
    color: theme.muted,
    fontSize: 12,
  },
  closedMeta: {
    color: theme.muted,
  },
  closedPay: {
    color: theme.primary,
    fontWeight: '700',
  },
  closedRating: {
    flexDirection: 'row',
    gap: 2,
  },
  closedFeedback: {
    color: theme.text,
    lineHeight: 18,
  },
  collectionCard: {
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    backgroundColor: '#FFFDFC',
  },
  collectionCardCompact: {
    padding: 14,
  },
  collectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  collectionTitle: {
    fontWeight: '700',
    color: theme.text,
    flex: 1,
    marginRight: 12,
  },
  collectionBadge: {
    backgroundColor: '#FFE3E3',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  collectionBadgeText: {
    color: theme.primary,
    fontSize: 12,
    fontWeight: '600',
  },
  collectionShift: {
    marginTop: 10,
    color: theme.muted,
    fontSize: 13,
  },
  collectionRate: {
    marginTop: 4,
    color: theme.primary,
    fontWeight: '700',
  },
  applyButton: {
    backgroundColor: theme.primary,
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: 'center',
  },
  applyButtonText: {
    color: '#fff',
    fontWeight: '700',
  },
  checkItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  checkBullet: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: theme.accent,
    marginRight: 10,
  },
  checkText: {
    color: theme.text,
    flex: 1,
  },
  secondaryButton: {
    marginTop: 12,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.primary,
    alignItems: 'center',
  },
  secondaryButtonText: {
    color: theme.primary,
    fontWeight: '600',
  },
  profileModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    padding: 16,
  },
  profileModalContent: {
    backgroundColor: '#fff',
    borderRadius: 20,
    paddingBottom: 16,
    maxHeight: '90%',
    width: '100%',
  },
  profileModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.border,
  },
  profileModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.text,
  },
  profileModalClose: {
    padding: 6,
  },
  profileModalBody: {
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  modalSecondaryButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: theme.primary,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  modalSecondaryButtonText: {
    color: theme.primary,
    fontWeight: '600',
  },
  modalPrimaryButton: {
    flex: 1,
    backgroundColor: theme.primary,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  modalPrimaryButtonText: {
    color: '#fff',
    fontWeight: '700',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  modalContent: {
    backgroundColor: '#fff',
    padding: 24,
    borderRadius: 18,
    width: '100%',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: theme.primary,
  },
  modalSubtitle: {
    color: theme.muted,
    marginTop: 8,
    marginBottom: 12,
  },
  modalUsage: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  modalDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: theme.primary,
    marginRight: 10,
  },
  modalUsageText: {
    color: theme.text,
    fontSize: 15,
  },
  closeButton: {
    marginTop: 16,
    backgroundColor: theme.primary,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  closeButtonText: {
    color: '#fff',
    fontWeight: '700',
  },
  timelineItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.border,
  },
  timelineItemCompact: {
    alignItems: 'flex-start',
    gap: 10,
  },
  timelineDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    marginRight: 12,
  },
  timelineDot_done: {
    backgroundColor: '#4CAF50',
  },
  timelineDot_upcoming: {
    backgroundColor: theme.primary,
  },
  timelineDot_alert: {
    backgroundColor: '#FF7043',
  },
  timelineContent: {
    flex: 1,
  },
  timelineTitle: {
    fontWeight: '700',
    color: theme.text,
  },
  timelineMeta: {
    color: theme.muted,
    fontSize: 13,
    marginTop: 2,
  },
  timelineAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: theme.primary,
  },
  timelineActionCompact: {
    marginTop: 8,
    alignSelf: 'flex-start',
  },
  timelineActionText: {
    color: theme.primary,
    fontSize: 12,
    fontWeight: '600',
  },
  chatCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
    gap: 12,
  },
  chatCardCompact: {
    alignItems: 'flex-start',
  },
  chatAvatar: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: '#FFE3E3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatAvatarText: {
    color: theme.primary,
    fontSize: 20,
    fontWeight: '700',
  },
  chatBody: {
    flex: 1,
  },
  chatHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  chatName: {
    fontWeight: '700',
    color: theme.text,
  },
  chatTime: {
    color: theme.muted,
    fontSize: 12,
  },
  chatSnippet: {
    color: theme.text,
    marginTop: 4,
  },
  chatStatus: {
    marginTop: 6,
    color: theme.primary,
    fontSize: 12,
    fontWeight: '600',
  },
  chatUnread: {
    backgroundColor: theme.primary,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  chatUnreadText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
  },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.border,
  },
  settingRowCompact: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 10,
  },
  settingBody: {
    flex: 1,
  },
  settingLabel: {
    fontWeight: '600',
    color: theme.text,
  },
  settingSubtitle: {
    color: theme.muted,
    fontSize: 13,
    marginTop: 2,
  },
  shortcutRow: {
    flexDirection: 'row',
    gap: 12,
    flexWrap: 'wrap',
  },
  shortcutCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 16,
    padding: 14,
    backgroundColor: '#FFFDFC',
    gap: 6,
    minWidth: 150,
  },
  shortcutTitle: {
    fontWeight: '700',
    color: theme.text,
  },
  shortcutSubtitle: {
    color: theme.muted,
    fontSize: 12,
  },
  sessionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
  },
  sessionLabel: {
    color: theme.muted,
    fontSize: 13,
  },
  sessionValue: {
    color: theme.text,
    fontWeight: '600',
    maxWidth: '60%',
    textAlign: 'right',
  },
  sessionToken: {
    fontSize: 12,
    color: theme.muted,
  },
  logoutButton: {
    marginTop: 12,
    backgroundColor: theme.primary,
    paddingVertical: 12,
    borderRadius: 14,
    alignItems: 'center',
  },
  logoutButtonDisabled: {
    backgroundColor: '#E0E0E0',
  },
  logoutButtonText: {
    color: '#fff',
    fontWeight: '700',
  },
  requestPermissionButton: {
    marginTop: 12,
    backgroundColor: theme.accent,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 14,
    alignItems: 'center',
  },
  requestPermissionButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 14,
  },
  reviewCard: {
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    backgroundColor: '#fff',
    gap: 6,
  },
  reviewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  reviewEmployer: {
    fontWeight: '700',
    color: theme.text,
  },
  reviewDate: {
    color: theme.muted,
    fontSize: 12,
  },
  reviewShift: {
    color: theme.muted,
  },
  reviewRating: {
    flexDirection: 'row',
    gap: 2,
    marginTop: 2,
  },
  reviewText: {
    color: theme.text,
    marginTop: 4,
    lineHeight: 18,
  },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 96,
    borderRadius: 999,
    boxShadow: '0px 8px 10px 0px rgba(198, 40, 40, 0.4)',
  },
  fabCompact: {
    right: 16,
    left: 16,
  },
  fabInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 999,
  },
  fabText: {
    color: '#fff',
    fontWeight: '700',
  },
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: '#fff',
    boxShadow: '0px -4px 10px 0px rgba(0, 0, 0, 0.08)',
    width: '100%',
    alignSelf: 'stretch',
  },
  bottomNavCompact: {
    paddingHorizontal: 12,
  },
  bottomNavItem: {
    alignItems: 'center',
    gap: 4,
  },
  bottomNavLabel: {
    color: '#A0A0A0',
    fontSize: 11,
    fontWeight: '600',
  },
  bottomNavLabelActive: {
    color: '#C62828',
  },
  authHero: {
    paddingHorizontal: 24,
    paddingVertical: 32,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    gap: 10,
  },
  authBadge: {
    textTransform: 'uppercase',
    letterSpacing: 2,
    color: '#FFDADA',
    fontWeight: '700',
  },
  authTitle: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '700',
  },
  authSubtitle: {
    color: '#FFECEC',
    fontSize: 14,
    lineHeight: 20,
  },
  authContent: {
    padding: 24,
    gap: 16,
    width: '100%',
  },
  authScroll: {
    width: '100%',
  },
  authCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 20,
    gap: 12,
    boxShadow: '0px 6px 14px 0px rgba(0, 0, 0, 0.06)',
    borderWidth: 1,
    borderColor: '#FFE8E8',
  },
  authCardTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: theme.text,
  },
  authCardSubtitle: {
    color: theme.muted,
    marginBottom: 4,
  },
  authModeTabs: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 8,
  },
  authModeButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: 'center',
  },
  authModeButtonActive: {
    backgroundColor: '#FFE3E3',
    borderColor: theme.primary,
  },
  authModeButtonText: {
    color: theme.muted,
    fontWeight: '600',
  },
  authModeButtonTextActive: {
    color: theme.primary,
  },
  authInput: {
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    color: theme.text,
  },
  authSubLabel: {
    marginTop: 6,
    marginBottom: 2,
    fontSize: 13,
    fontWeight: '600',
    color: theme.muted,
  },
  authPrimaryBtn: {
    backgroundColor: theme.primary,
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
    marginTop: 4,
  },
  authPrimaryBtnDisabled: {
    opacity: 0.5,
  },
  authPrimaryText: {
    color: '#fff',
    fontWeight: '700',
  },
  // googleButton: {
  //   flexDirection: 'row',
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   gap: 8,
  //   paddingVertical: 12,
  //   borderRadius: 14,
  //   borderWidth: 1,
  //   borderColor: theme.primary,
  // },
  // googleButtonDisabled: {
  //   opacity: 0.5,
  // },
  // googleButtonText: {
  //   color: theme.primary,
  //   fontWeight: '600',
  // },
  authLinksRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 8,
    marginTop: 4,
  },
  authLink: {
    textAlign: 'center',
    color: theme.primary,
    fontWeight: '600',
    marginTop: 4,
  },
  verificationBlock: {
    borderWidth: 1,
    borderColor: '#FFE0E0',
    borderRadius: 16,
    padding: 12,
    gap: 8,
    marginTop: 6,
  },
  verificationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  verificationLabel: {
    fontWeight: '600',
    color: theme.text,
  },
  verificationStatusSuccess: {
    color: '#2E7D32',
    fontSize: 12,
    fontWeight: '700',
  },
  verificationAction: {
    borderWidth: 1,
    borderColor: theme.primary,
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: 'center',
  },
  verificationActionDisabled: {
    borderColor: theme.border,
    backgroundColor: '#F5F5F5',
    opacity: 0.7,
  },
  verificationActionText: {
    color: theme.primary,
    fontWeight: '600',
  },
  authBenefits: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: '#FFE8E8',
    gap: 12,
  },
  roleSwitcher: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  roleButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: theme.primary,
    borderRadius: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  roleButtonActive: {
    backgroundColor: theme.primary,
  },
  roleButtonText: {
    color: theme.primary,
    fontWeight: '600',
  },
  roleButtonTextActive: {
    color: '#fff',
  },
  roleHint: {
    color: theme.muted,
    fontSize: 13,
    marginTop: 6,
    marginBottom: 4,
  },
  authBenefit: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
  },
  authBenefitIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#FFE3E3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  authBenefitBody: {
    flex: 1,
  },
  authBenefitTitle: {
    fontWeight: '700',
    color: theme.text,
  },
  authBenefitSubtitle: {
    color: theme.muted,
    fontSize: 13,
    marginTop: 2,
  },
  authSkip: {
    textAlign: 'center',
    color: theme.muted,
    fontWeight: '600',
    marginTop: 6,
  },
  // Стили для вакансий
  viewToggleContainer: {
    flexDirection: 'row',
    marginHorizontal: 16,
    marginVertical: 12,
    backgroundColor: theme.card,
    borderRadius: 12,
    padding: 4,
    borderWidth: 1,
    borderColor: theme.border,
  },
  viewToggleButton: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 8,
  },
  viewToggleButtonActive: {
    backgroundColor: theme.primary,
  },
  viewToggleText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.muted,
  },
  viewToggleTextActive: {
    color: '#fff',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.card,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: theme.border,
    gap: 8,
  },
  searchIcon: {
    marginRight: 4,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: theme.text,
    padding: 0,
  },
  searchClearButton: {
    padding: 4,
  },
  filterRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
  },
  filterInputContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.card,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: theme.border,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  filterInputIcon: {
    marginRight: 8,
  },
  filterInput: {
    flex: 1,
    fontSize: 15,
    color: theme.text,
    padding: 0,
    margin: 0,
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  loadingText: {
    marginTop: 12,
    color: theme.muted,
    fontSize: 14,
  },
  errorContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  errorText: {
    color: theme.muted,
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 16,
  },
  retryButton: {
    backgroundColor: theme.primary,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  retryButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 14,
  },
  emptyContainer: {
    alignItems: 'center',
    paddingVertical: 60,
  },
  emptyText: {
    marginTop: 16,
    fontSize: 16,
    fontWeight: '600',
    color: theme.text,
    textAlign: 'center',
  },
  emptySubtext: {
    marginTop: 8,
    fontSize: 14,
    color: theme.muted,
    textAlign: 'center',
  },
  applicationCard: {
    backgroundColor: theme.card,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: theme.border,
  },
  applicationCardCompact: {
    padding: 12,
  },
  applicationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  applicationJobTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
    color: theme.text,
    marginRight: 8,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  statusBadgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },
  applicationCompany: {
    fontSize: 14,
    color: theme.muted,
    marginBottom: 4,
  },
  applicationDate: {
    fontSize: 12,
    color: theme.muted,
    marginBottom: 8,
  },
  applicationMessage: {
    fontSize: 14,
    color: theme.text,
    marginTop: 8,
    lineHeight: 20,
  },
  jobLocation: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    gap: 4,
  },
  jobLocationText: {
    fontSize: 14,
    color: theme.muted,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: theme.background,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
    backgroundColor: theme.card,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.text,
  },
  modalCloseButton: {
    padding: 4,
  },
  modalContent: {
    flex: 1,
    padding: 16,
  },
  jobDetailTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: theme.text,
    marginBottom: 8,
  },
  jobDetailCompany: {
    fontSize: 18,
    color: theme.muted,
    marginBottom: 12,
  },
  jobDetailSalary: {
    fontSize: 20,
    fontWeight: '600',
    color: theme.primary,
    marginBottom: 16,
  },
  jobDetailLocation: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    gap: 6,
  },
  jobDetailLocationText: {
    fontSize: 16,
    color: theme.muted,
  },
  jobDetailSection: {
    marginBottom: 24,
  },
  jobDetailSectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.text,
    marginBottom: 12,
  },
  jobDetailDescription: {
    fontSize: 15,
    color: theme.text,
    lineHeight: 22,
  },
  messageInput: {
    backgroundColor: theme.card,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: theme.border,
    fontSize: 15,
    color: theme.text,
    minHeight: 100,
    marginTop: 8,
  },
  chatModal: {
    flex: 1,
    backgroundColor: theme.background,
  },
  chatModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: theme.card,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  chatModalBackButton: {
    padding: 8,
    marginRight: 8,
  },
  chatModalHeaderInfo: {
    flex: 1,
  },
  chatModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.text,
  },
  chatMessages: {
    flex: 1,
    backgroundColor: theme.background,
  },
  chatMessagesContent: {
    padding: 16,
    gap: 12,
  },
  chatMessage: {
    flexDirection: 'row',
    marginBottom: 8,
    alignItems: 'flex-end',
  },
  chatMessageMy: {
    justifyContent: 'flex-end',
  },
  chatMessageOther: {
    justifyContent: 'flex-start',
  },
  chatMessageBubble: {
    maxWidth: '75%',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 18,
  },
  chatMessageBubbleMy: {
    backgroundColor: theme.primary,
    borderBottomRightRadius: 4,
  },
  chatMessageBubbleOther: {
    backgroundColor: theme.card,
    borderBottomLeftRadius: 4,
    borderWidth: 1,
    borderColor: theme.border,
  },
  chatMessageText: {
    fontSize: 15,
    lineHeight: 20,
  },
  chatMessageTextMy: {
    color: '#fff',
  },
  chatMessageTextOther: {
    color: theme.text,
  },
  chatMessageTime: {
    fontSize: 11,
    marginTop: 4,
  },
  chatMessageTimeMy: {
    color: 'rgba(255, 255, 255, 0.7)',
    textAlign: 'right',
  },
  chatMessageTimeOther: {
    color: theme.muted,
    textAlign: 'left',
  },
  chatInputContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: theme.card,
    borderTopWidth: 1,
    borderTopColor: theme.border,
    gap: 8,
  },
  chatInput: {
    flex: 1,
    backgroundColor: theme.background,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 15,
    color: theme.text,
    maxHeight: 100,
    borderWidth: 1,
    borderColor: theme.border,
  },
  chatSendButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatSendButtonDisabled: {
    opacity: 0.5,
  },
  // Стили для документов
  documentsActionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 20,
  },
  documentActionCard: {
    flex: 1,
    minWidth: '30%',
    backgroundColor: theme.card,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.border,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  documentActionCardDisabled: {
    opacity: 0.6,
  },
  documentActionIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: '#FFF5F5',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  documentActionCardTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.text,
    textAlign: 'center',
    marginBottom: 4,
  },
  documentActionCardSubtitle: {
    fontSize: 12,
    color: theme.muted,
    textAlign: 'center',
  },
  documentsList: {
    gap: 12,
  },
  documentCard: {
    backgroundColor: theme.card,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.border,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  documentCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 12,
  },
  documentCardIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: '#FFF5F5',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  documentCardInfo: {
    flex: 1,
    minWidth: 0,
  },
  documentCardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.text,
    marginBottom: 4,
  },
  documentCardDescription: {
    fontSize: 13,
    color: theme.muted,
    marginBottom: 4,
  },
  documentCardDate: {
    fontSize: 12,
    color: theme.muted,
    marginTop: 2,
  },
  documentStatusBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    flexShrink: 0,
  },
  documentStatusText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#fff',
  },
  documentCardActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: theme.border,
    position: 'relative',
    zIndex: 10,
  },
  documentCardButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: theme.background,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.border,
    flex: 1,
    minHeight: 44,
    zIndex: 1,
  },
  documentCardButtonDanger: {
    borderColor: '#EF5350',
    cursor: 'pointer',
  },
  documentCardButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: theme.primary,
  },
  documentCardButtonTextDanger: {
    color: '#EF5350',
  },
  viewAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: 16,
    backgroundColor: theme.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.border,
    marginTop: 8,
  },
  viewAllButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.primary,
  },
  modalSafeArea: {
    flex: 1,
    backgroundColor: theme.background,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: theme.card,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: theme.text,
  },
  modalCloseButton: {
    padding: 8,
  },
  modalContent: {
    flex: 1,
    padding: 16,
  },
  modalFooter: {
    padding: 16,
    backgroundColor: theme.card,
    borderTopWidth: 1,
    borderTopColor: theme.border,
    gap: 8,
  },
  documentActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: theme.primary,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.primary,
  },
  documentActionButtonDanger: {
    backgroundColor: '#FFF5F5',
    borderColor: '#EF5350',
  },
  documentActionButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  documentActionButtonTextDanger: {
    color: '#EF5350',
  },
  documentDescription: {
    fontSize: 16,
    color: theme.text,
    marginBottom: 12,
    lineHeight: 22,
  },
  documentDate: {
    fontSize: 14,
    color: theme.muted,
    marginBottom: 16,
  },
  documentViewer: {
    marginTop: 16,
  },
  documentViewerContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 32,
    backgroundColor: theme.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.border,
  },
  documentImageContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 32,
    backgroundColor: theme.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.border,
  },
  documentViewerText: {
    fontSize: 16,
    color: theme.text,
    marginTop: 16,
    textAlign: 'center',
  },
  documentViewerLink: {
    fontSize: 16,
    color: theme.primary,
    marginTop: 8,
    textDecorationLine: 'underline',
    textAlign: 'center',
  },
  documentViewerButton: {
    marginTop: 16,
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: theme.primary,
    borderRadius: 12,
  },
  documentViewerButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  reviewFormContainer: {
    padding: 16,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginVertical: 12,
  },
  starButton: {
    padding: 4,
  },
  ratingHint: {
    fontSize: 14,
    color: theme.muted,
    textAlign: 'center',
    marginTop: 8,
  },
  sectionActionHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginBottom: 12,
  },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: theme.card,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.border,
  },
  addButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.primary,
  },
  characterCount: {
    fontSize: 12,
    color: theme.muted,
    marginTop: 4,
    textAlign: 'right',
  },
});
